version: '3.8'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: cungcungcung
      MYSQL_DATABASE: exe_dtb
    ports:
      - '3306:3306'
    networks:
      - exe_network
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    image: anticode42/exe-be:latest
    ports:
      - '5000:5000'
    environment:
      - DB_HOST=db
      - DB_USERNAME=root
      - DB_PASSWORD=cungcungcung
      - DB_NAME=exe_dtb
    networks:
      - exe_network
    depends_on:
      db:
        condition: service_healthy

networks:
  exe_network:
